apiVersion: v1
kind: ReplicationController
metadata:
  name: qperf-server
  namespace: default
  labels:
    k8s-app: qperf-server
spec:
  replicas: 1
  selector:
    k8s-app: qperf-server
  template:
    metadata:
      labels:
        k8s-app: qperf-server
    spec:
      containers:
      - image: "arjanschaaf/centos-qperf"
        args: ["-lp", "4000"]
        imagePullPolicy: "IfNotPresent"
        name: "qperf-server"
        ports:
            - containerPort: 4000
              name: "p1udp"
              protocol: UDP
            - containerPort: 4000
              name: "p1tcp"
              protocol: TCP
            - containerPort: 4001
              name: "p2tcp"
              protocol: TCP
            - containerPort: 4001
              name: "p2udp"
              protocol: UDP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: "qperf-server"
  namespace: "default"
spec:
  selector:
    k8s-app: "qperf-server"
  ports:
  - name: "p1udp"
    port: 4000
    targetPort: 4000
    protocol: UDP
  - name: "p1tcp"
    port: 4000
    targetPort: 4000
    protocol: TCP
  - name: "p2udp"
    port: 4001
    targetPort: 4001
    protocol: UDP
  - name: "p2tcp"
    port: 4001
    targetPort: 4001
    protocol: TCP
