apiVersion: v1
kind: Pod
metadata:
  name: qperf-server
  namespace: default
spec:
  containers:
  - image: arjanschaaf/centos-qperf
    args: ["-lp", "4000"]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  
---
apiVersion: v1
kind: Service
metadata:
  name: qperf-server
  namespace: default
spec:
  selector:
    name: qperf-server
  ports: [4000, 4001]
