apiVersion: v1
kind: Pod
metadata:
  name: qperf-server
  namespace: default
spec:
  containers:
  - image: arjanschaaf/centos-qperf
    args: ["-lp", "4000"]
    imagePullPolicy: IfNotPresent
    ports:
        - containerPort: 4000
          name: p1udp
          protocol: UDP
        - containerPort: 4000
          name: p1tcp
          protocol: TCP
        - containerPort: 4001
          name: p2tcp
          protocol: TCP
        - containerPort: 4001
          name: p2udp
          protocol: UDP
  restartPolicy: Always
  
---
apiVersion: v1
kind: Service
metadata:
  name: qperf-server
  namespace: default
spec:
  selector:
    name: qperf-server
  ports:
  - name: p1udp
    port: 4000
    protocol: UDP
  - name: p1tcp
    port: 4000
    protocol: TCP
  - name: p2udp
    port: 4001
    protocol: UDP
  - name: p2tcp
    port: 4001
    protocol: TCP
